AccessRole:
  Metadata:
    {{- if .PermissionsBoundary}}
    'aws:copilot:description': 'An IAM Role with permissions boundary {{.PermissionsBoundary}} for App Runner to use on your behalf to pull your image from ECR'
    {{- else}}
    'aws:copilot:description': 'An IAM Role for App Runner to use on your behalf to pull your image from ECR'
    {{- end}}
  Type: AWS::IAM::Role
  Condition: NeedsAccessRole
  Properties:
    {{- if .PermissionsBoundary}}
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/{{.PermissionsBoundary}}'
    {{- end}}
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - build.apprunner.amazonaws.com
          Action: sts:AssumeRole

    ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess
