AddonsStack:
  Metadata:
    'aws:copilot:description': 'An Addons CloudFormation Stack for your additional AWS resources'
  Type: AWS::CloudFormation::Stack
{{- if gt (len (envControllerParams .)) 0}}
  DependsOn: EnvControllerAction
{{- end}}
  Condition: HasAddons
  Properties:
    Parameters:
      App: !Ref AppName
      Env: !Ref EnvName
      Name: !Ref WorkloadName
      {{- if .AddonsExtraParams }}
{{ .AddonsExtraParams | indent 6 }}
      {{- end}}
    TemplateURL:
      !Ref AddonsTemplateURL