{{- if or .ALBEnabled .Autoscaling}}
CustomResourceRole:
  Metadata:
    "aws:copilot:description": "An IAM role used by custom resources to describe your ECS service"
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: 2012-10-17
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:
            - sts:AssumeRole
    Path: /
    ManagedPolicyArns:
      - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Policies:
      {{- if .ALBEnabled}}
      - PolicyName: "DNSandACMAccess"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - elasticloadbalancing:DescribeRules
              Resource: "*"
      {{- end}}
      {{- if .Autoscaling}}
      - PolicyName: "DelegateDesiredCountAccess"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: ECS
              Effect: Allow
              Action:
                - ecs:DescribeServices
              Resource: "*"
              Condition:
                ArnEquals:
                  "ecs:cluster":
                    Fn::Sub:
                      - arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterName}
                      - ClusterName:
                          Fn::ImportValue:
                            !Sub "${AppName}-${EnvName}-ClusterId"
            - Sid: ResourceGroups
              Effect: Allow
              Action:
                - resource-groups:GetResources
              Resource: "*"
            - Sid: Tags
              Effect: Allow
              Action:
                - "tag:GetResources"
              Resource: "*"
      {{- end}}
{{- end}}