HTTPRulePriorityAction:
  Metadata:
    'aws:copilot:description': 'A custom resource assigning priority for HTTP listener rules'
  Type: Custom::RulePriorityFunction
  Properties:
    ServiceToken: !GetAtt RulePriorityFunction.Arn
    ListenerArn: !GetAtt EnvControllerAction.HTTPListenerArn

HTTPListenerRule:
  Metadata:
    'aws:copilot:description': 'A HTTP listener rule for forwarding HTTP traffic'
  Type: AWS::ElasticLoadBalancingV2::ListenerRule
  Properties:
    Actions:
      - TargetGroupArn: !Ref TargetGroup
        Type: forward
    Conditions:
    {{- if .AllowedSourceIps}}
      - Field: 'source-ip'
        SourceIpConfig:
          Values:
          {{- range $sourceIP := .AllowedSourceIps}}
          - {{$sourceIP}}
          {{- end}}
    {{- end}}
      - Field: 'path-pattern'
        PathPatternConfig:
          Values:
            !If
              - IsDefaultRootPath
              -
                - "/*"
              -
                - !Sub "/${RulePath}"
                - !Sub "/${RulePath}/*"
    ListenerArn: !GetAtt EnvControllerAction.HTTPListenerArn
    Priority: 
      !If
        - IsDefaultRootPath
        - 50000 # This is the max rule priority. Since this rule evaluates true for everything, we make sure it is last
        - !GetAtt HTTPRulePriorityAction.Priority