{{- if not .Aliases}}
LoadBalancerDNSAlias:
  Metadata:
    'aws:copilot:description': 'The default alias record for the application load balancer'
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneId:
      Fn::ImportValue:
        !Sub "${AppName}-${EnvName}-HostedZone"
    Comment: !Sub "LoadBalancer alias for service ${WorkloadName}"
    RecordSets:
    - Name:
        !Join
          - '.'
          - - !Ref WorkloadName
            - Fn::ImportValue:
                !Sub "${AppName}-${EnvName}-SubDomain"
            - ""
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt EnvControllerAction.PublicLoadBalancerHostedZone
        DNSName: !GetAtt EnvControllerAction.PublicLoadBalancerDNSName
{{- else}}
{{- range $hostedZoneID, $aliases := .HostedZoneAliases}}
LoadBalancerDNSAlias{{$hostedZoneID}}:
  Metadata:
    'aws:copilot:description': 'Alias records for the application load balancer in hosted zone {{$hostedZoneID}}'
  Type: AWS::Route53::RecordSetGroup
  Properties:
    HostedZoneId: {{$hostedZoneID}}
    Comment: !Sub "LoadBalancer aliases for service ${WorkloadName} in hosted zone {{$hostedZoneID}}"
    RecordSets:
    {{- range $alias := $aliases}}
      - Name: {{quote $alias}}
        Type: A
        AliasTarget:
          {{- if eq $.WorkloadType "Backend Service"}}
          HostedZoneId: !GetAtt EnvControllerAction.InternalLoadBalancerHostedZone
          DNSName: !GetAtt EnvControllerAction.InternalLoadBalancerDNSName
          {{- else}}
          HostedZoneId: !GetAtt EnvControllerAction.PublicLoadBalancerHostedZone
          DNSName: !GetAtt EnvControllerAction.PublicLoadBalancerDNSName
          {{- end}}
    {{- end}}
{{- end}}
{{- end}}

HTTPSRulePriorityAction:
  Metadata:
    'aws:copilot:description': 'A custom resource assigning priority for HTTPS listener rules'
  Type: Custom::RulePriorityFunction
  Properties:
    ServiceToken: !GetAtt RulePriorityFunction.Arn
    RulePath: !Ref RulePath
    {{- if eq .WorkloadType "Backend Service"}}
    ListenerArn: !GetAtt EnvControllerAction.InternalHTTPSListenerArn
    {{- else}}
    ListenerArn: !GetAtt EnvControllerAction.HTTPSListenerArn
    {{- end}}

HTTPRuleWithDomainPriorityAction:
  Metadata:
    'aws:copilot:description': 'A custom resource assigning priority for HTTP listener rules'
  Type: Custom::RulePriorityFunction
  Properties:
    ServiceToken: !GetAtt RulePriorityFunction.Arn
    RulePath: !Ref RulePath
    {{- if eq .WorkloadType "Backend Service"}}
    ListenerArn: !GetAtt EnvControllerAction.InternalHTTPListenerArn
    {{- else}}
    ListenerArn: !GetAtt EnvControllerAction.HTTPListenerArn
    {{- end}}

HTTPListenerRuleWithDomain:
  Metadata:
    'aws:copilot:description': 'An HTTP listener rule that redirects HTTP to HTTPS'
  Type: AWS::ElasticLoadBalancingV2::ListenerRule
  Properties:
    Actions:
      - Type: redirect
        RedirectConfig:
          Protocol: HTTPS
          Port: 443
          Host: "#{host}"
          Path: "/#{path}"
          Query: "#{query}"
          StatusCode: HTTP_301
    Conditions:
{{- if .Aliases }}
      - Field: 'host-header'
        HostHeaderConfig:
          Values: {{ fmtSlice (quoteSlice .Aliases) }}
{{- else }}
      - Field: 'host-header'
        HostHeaderConfig:
          Values:
            - Fn::Join:
              - '.'
              - - !Ref WorkloadName
                - Fn::ImportValue:
                    !Sub "${AppName}-${EnvName}-SubDomain"
{{- end}}
      - Field: 'path-pattern'
        PathPatternConfig:
          Values:
            !If
              - IsDefaultRootPath
              -
                - "/*"
              -
                - !Sub "/${RulePath}"
                - !Sub "/${RulePath}/*"
    {{- if eq .WorkloadType "Backend Service"}}
    ListenerArn: !GetAtt EnvControllerAction.InternalHTTPListenerArn
    {{- else}}
    ListenerArn: !GetAtt EnvControllerAction.HTTPListenerArn
    {{- end}}
    Priority: !GetAtt HTTPRuleWithDomainPriorityAction.Priority

HTTPSListenerRule:
  Metadata:
    'aws:copilot:description': 'An HTTPS listener rule for forwarding HTTPS traffic to your tasks'
  Type: AWS::ElasticLoadBalancingV2::ListenerRule
  Properties:
    Actions:
      - TargetGroupArn: !Ref TargetGroup
        Type: forward
    Conditions:
{{- if .AllowedSourceIps}}
      - Field: 'source-ip'
        SourceIpConfig:
          Values:
{{- range $sourceIP := .AllowedSourceIps}}
          - {{$sourceIP}}
{{- end}}
{{- end}}
{{- if .Aliases }}
      - Field: 'host-header'
        HostHeaderConfig:
          Values: {{ fmtSlice (quoteSlice .Aliases) }}
{{- else }}
      - Field: 'host-header'
        HostHeaderConfig:
          Values:
            - Fn::Join:
              - '.'
              - - !Ref WorkloadName
                - Fn::ImportValue:
                    !Sub "${AppName}-${EnvName}-SubDomain"
{{- end}}
      - Field: 'path-pattern'
        PathPatternConfig:
          Values:
            !If
              - IsDefaultRootPath
              -
                - "/*"
              -
                - !Sub "/${RulePath}"
                - !Sub "/${RulePath}/*"
    {{- if eq .WorkloadType "Backend Service"}}
    ListenerArn: !GetAtt EnvControllerAction.InternalHTTPSListenerArn
    {{- else}}
    ListenerArn: !GetAtt EnvControllerAction.HTTPSListenerArn
    {{- end}}
    Priority: !GetAtt HTTPSRulePriorityAction.Priority