InstanceRole:
  Metadata:
    'aws:copilot:description': 'An IAM role to control permissions for the containers in your service'
  Type: AWS::IAM::Role
  Properties:
  {{- if .NestedStack}}{{$stackName := .NestedStack.StackName}}
    {{- if gt (len .NestedStack.PolicyOutputs) 0}}
    ManagedPolicyArns:
    {{- range $managedPolicy := .NestedStack.PolicyOutputs}}
    - Fn::GetAtt: [{{$stackName}}, Outputs.{{$managedPolicy}}]
    {{- end}}
    {{- end}}
  {{- end}}
    AssumeRolePolicyDocument:
      Statement:
        - Effect: Allow
          Principal:
            Service: tasks.apprunner.amazonaws.com
          Action: 'sts:AssumeRole'
