{{- if .LogConfig}}LogConfiguration:
  LogDriver: awsfirelens
{{- if .LogConfig.Destination}}
  Options:{{range $name, $value := .LogConfig.Destination}}
    {{$name}}: {{$value | printf "%q"}}{{end}}
{{- end}}
{{- if .LogConfig.SecretOptions}}
  SecretOptions:
  {{- range $name, $secret := .LogConfig.SecretOptions}}
    - Name: {{$name}}
    {{- if $secret.RequiresImport}}
      ValueFrom:
        Fn::ImportValue: {{ quote $secret.ValueFrom -}}
    {{- else}}
      ValueFrom: {{if not $secret.RequiresSub }} {{$secret.ValueFrom}} {{- else}} !Sub 'arn:${AWS::Partition}:{{$secret.Service}}:${AWS::Region}:${AWS::AccountId}:{{$secret.ValueFrom}}' {{- end}}
    {{- end}}
  {{- end}}
{{- end}}
{{- else}}LogConfiguration:
  LogDriver: awslogs
  Options:
    awslogs-region: !Ref AWS::Region
    awslogs-group: !Ref LogGroup
    awslogs-stream-prefix: copilot
{{- end}}