LogGroup:
  Metadata:
    'aws:copilot:description': 'A CloudWatch log group to hold your service logs'
  Type: AWS::Logs::LogGroup
  Properties:
    LogGroupName: !Join ['', [/copilot/, !Ref AppName, '-', !Ref EnvName, '-', !Ref WorkloadName]]
    RetentionInDays: !Ref LogRetention