{{- if .Publish}}
{{- range $topic := .Publish.Topics}}
{{logicalIDSafe $topic.Name}}SNSTopic:
  Metadata:
    'aws:copilot:description': {{ if or $topic.Fifo.Enable $topic.Fifo.ContentBasedDeduplication }} 'A FIFO SNS topic to broadcast {{$topic.Name}} events' {{ else}} 'A SNS topic to broadcast {{$topic.Name}} events'{{ end}}
  Type: AWS::SNS::Topic
  Properties:
    {{- if or $topic.Fifo.Enable $topic.Fifo.ContentBasedDeduplication }}
    TopicName: !Sub '${AWS::StackName}-{{$topic.Name}}.fifo'
    {{- else}}
    TopicName: !Sub '${AWS::StackName}-{{$topic.Name}}'
    {{- end}}
    {{- if or $topic.Fifo.Enable $topic.Fifo.ContentBasedDeduplication }}
    FifoTopic: true
    {{- end}}
    KmsMasterKeyId: 'alias/aws/sns'
    {{- if $topic.Fifo.ContentBasedDeduplication }}
    ContentBasedDeduplication: true
    {{- end}}
{{logicalIDSafe $topic.Name}}SNSTopicPolicy:
  Type: AWS::SNS::TopicPolicy
  DependsOn: {{logicalIDSafe $topic.Name}}SNSTopic
  Properties:
    Topics:
      - !Ref {{logicalIDSafe $topic.Name}}SNSTopic
    PolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            AWS: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:root'
          Action:
            - sns:Subscribe
          Resource: !Ref {{logicalIDSafe $topic.Name}}SNSTopic
          Condition:
            StringEquals:
              "sns:Protocol": "sqs"
{{- end}}
{{- end}}