{{- if .DeploymentConfiguration.Rollback.CPUUtilization}}
CPURollbackAlarm:
  Metadata:
    'aws:copilot:description': "A CloudWatch alarm associated with CPU utilization for deployment rollbacks"
  Type: AWS::CloudWatch::Alarm
  DependsOn: Service
  Properties:
    AlarmDescription: "Roll back ECS service if CPU utilization is greater or equal to {{.DeploymentConfiguration.Rollback.CPUUtilization}}% twice in 2 minutes."
    AlarmName: {{.DeploymentConfiguration.Rollback.TruncateAlarmName .AppName .EnvName .WorkloadName "CopilotRollbackCPUAlarm"}}
    Namespace: 'AWS/ECS'
    Dimensions:
      - Name: ServiceName
        Value: !Ref Service
    MetricName: 'CPUUtilization'
    ComparisonOperator: 'GreaterThanOrEqualToThreshold'
    DatapointsToAlarm: 2
    EvaluationPeriods: 2
    Period: 60
    Statistic: 'Average'
    Threshold: {{.DeploymentConfiguration.Rollback.CPUUtilization}}
    Unit: 'Percent'
{{- end}}
  
{{- if .DeploymentConfiguration.Rollback.MemoryUtilization}}
MemoryRollbackAlarm:
  Metadata:
    'aws:copilot:description': "A CloudWatch alarm associated with memory utilization for deployment rollbacks"
  Type: AWS::CloudWatch::Alarm
  DependsOn: Service
  Properties:
    AlarmDescription: "Roll back ECS service if memory utilization is greater or equal to {{.DeploymentConfiguration.Rollback.MemoryUtilization}}% twice in 2 minutes."
    AlarmName: {{.DeploymentConfiguration.Rollback.TruncateAlarmName .AppName .EnvName .WorkloadName "CopilotRollbackMemAlarm"}}
    Namespace: 'AWS/ECS'
    Dimensions:
      - Name: ServiceName
        Value: !Ref Service
    MetricName: 'MemoryUtilization'
    ComparisonOperator: 'GreaterThanOrEqualToThreshold'
    DatapointsToAlarm: 2
    EvaluationPeriods: 2
    Period: 60
    Statistic: 'Average'
    Threshold: {{.DeploymentConfiguration.Rollback.MemoryUtilization}}
    Unit: 'Percent'
{{- end}}
