ScheduleTrigger:
  Metadata:
    'aws:copilot:description': "An EventBridge Schedule to trigger the job's state machine"
  Type: AWS::Scheduler::Schedule
  Properties:
    ScheduleExpressionTimezone: !Ref ScheduleTimezone
    {{- if eq .ScheduleExpression "none"}}
    ScheduleExpression: "rate(5 minutes)"
    State: DISABLED
    {{- else }}
    ScheduleExpression: !Ref Schedule
    State: ENABLED
    {{- end }}
    FlexibleTimeWindow:
      Mode: "OFF"
    Target:
      Arn: !Ref StateMachine
      RoleArn: !GetAtt ScheduleTriggerRole.Arn
ScheduleTriggerRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
      - Effect: Allow
        Principal:
          Service: scheduler.amazonaws.com
        Action: sts:AssumeRole
    {{- if .PermissionsBoundary}}
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/{{.PermissionsBoundary}}'
    {{- end}}
    Policies:
    - PolicyName: SchedulePolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: states:StartExecution
          Resource: !Ref StateMachine
