# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: '2010-09-09'{{$accounts := .Accounts}}{{$app := .App}}{{$services := .Services}}{{$svcTag := .ServiceTagKey}}
# Cross-regional resources deployed via a stackset in the tools account
# to support the CodePipeline for a workspace
Description: Cross-regional resources to support the CodePipeline for a workspace
Metadata:
  TemplateVersion: 'v1.0.2'
  Version: {{.Version}}
  Services:{{if not $services}} []{{else}}{{range $service := $services}}
  - {{$service}}{{end}}{{end}}
  Accounts:{{if not $accounts}} []{{else}}{{range $account := $accounts}}
  - {{$account}}{{end}}{{end}}
Resources:
  KMSKey:
    # Used by the CodePipeline in the tools account to en/decrypt the
    # artifacts between stages
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: !Ref AWS::StackName
        Statement:
          -
            # Allows the key to be administered in the tools account
            Effect: Allow
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
              - "kms:Tag*"
              - "kms:UntagResource"
            Resource: "*"
          -
            # Allow use of the key in the tools account and all environment accounts
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root{{range $accounts}}
                - !Sub arn:${AWS::Partition}:iam::{{.}}:root{{end}}
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: "*"
  PipelineBuiltArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: PipelineBuiltArtifactBucket
    Properties:
      Bucket: !Ref PipelineBuiltArtifactBucket
      PolicyDocument:
        Statement:
          -
            Action:
              - s3:*
            Effect: Allow
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${PipelineBuiltArtifactBucket}
              - !Sub arn:${AWS::Partition}:s3:::${PipelineBuiltArtifactBucket}/*
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root{{range $accounts}}
                - !Sub arn:${AWS::Partition}:iam::{{.}}:root{{end}}
  PipelineBuiltArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

{{range $service := $services}}
  ECRRepo{{logicalIDSafe $service}}:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: {{$app}}/{{$service}}
      Tags:
        -
          Key: {{$svcTag}}
          Value: {{$service}}
      RepositoryPolicyText:
        Version: '2008-10-17'
        Statement:
        - Sid: AllowPushPull
          Effect: Allow
          Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root{{range $accounts}}
                - !Sub arn:${AWS::Partition}:iam::{{.}}:root{{end}}
          Action:
          - ecr:GetDownloadUrlForLayer
          - ecr:BatchGetImage
          - ecr:BatchCheckLayerAvailability
          - ecr:PutImage
          - ecr:InitiateLayerUpload
          - ecr:UploadLayerPart
          - ecr:CompleteLayerUpload
{{end}}
Outputs:
  KMSKeyARN:
    Description: KMS Key used by CodePipeline for encrypting artifacts.
    Value: !GetAtt KMSKey.Arn
    Export:
      Name: {{$app}}-ArtifactKey
  PipelineBucket:
    Description: Bucket used for CodePipeline to stage resources in.
    Value: !Ref PipelineBuiltArtifactBucket
{{- range $service := $services}} 
  ECRRepo{{logicalIDSafe $service}}:
    Description: ECR Repo used to store images of the {{$service}} service.
    Value: !GetAtt ECRRepo{{logicalIDSafe $service}}.Arn
{{- end}}
  TemplateVersion:
    Description: Required output to force the stackset to update if mutating version.
    Value: {{.TemplateVersion}}
