issues:
  include:
    - EXC0012 # comment on exported fields
    - EXC0014 # comment in correct format on exported fields
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: internal/pkg/exec/(.+)\.go
      text: 'is unused'
    - text: "S1009: should omit nil check" # TODO: remove this line after fixing all the issues
      linters:
        - gosimple
    - text: "printf: non-constant format string in call to" # TODO: remove this line after fixing all the issues
      linters:
        - govet



linters:
  enable:
    - revive
    - testifylint

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  testifylint:
    disable-all: true
    enable:
      - error-nil
