{{- if .Publish}}
{{- range $topic := .Publish.Topics}}
{{logicalIDSafe $topic.Name}}SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ${AWS::StackName}-{{logicalIDSafe $topic.Name}}
  
  {{- if $topic.AllowedWorkers}}
  {{logicalIDSafe $topic.Name}}SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    DependsOn: {{logicalIDSafe $topic.Name}}SNSTopic
    Properties:
      Topics: 
        - !Ref {{logicalIDSafe $topic.Name}}SNSTopic
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          {{- range $worker := $topic.AllowedWorkers}}
          - Effect: Allow
            Principal:
              Service: sqs.amazonaws.com
            Action: 
              - sns:Subscribe
            Resource: !Sub 'arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:*'
            Condition:
              StringEquals:
                'sqs:ResourceTag/copilot-application': !Sub '${AppName}'
                'sqs:ResourceTag/copilot-environment': !Sub '${EnvName}'
                'sqs:ResourceTag/copilot-service': '{{$worker}}'
          {{- end}}
  {{- end}}
{{- end}}
{{- end}}