{{- range $stage := .Stages}}
{{- range $action := $stage.PreDeployments}}
Pre{{logicalIDSafe $stage.Name}}DeploymentAction{{logicalIDSafe $action.Name}}BuildProjectRole:
  Type: AWS::IAM::Role
  Properties:
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service:
              - codebuild.amazonaws.com
          Action:
            - sts:AssumeRole
    Path: /
    ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess' # for env ls
      - 'arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess' # for service package
    {{- if $.PermissionsBoundary }}
    PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/{{$.PermissionsBoundary}}'
    {{- end }}
    Policies:
      - PolicyName: assume-env-manager
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Resource: 'arn:aws:iam::{{$stage.AccountID}}:role/{{$.AppName}}-{{$stage.Name}}-EnvManagerRole'
            Action:
              - sts:AssumeRole
      - PolicyName: codebuild-policy
        PolicyDocument:
{{ include "build-role-policy-document" $ | indent 10 }}

Pre{{logicalIDSafe $stage.Name}}DeploymentAction{{logicalIDSafe $action.Name}}:
  Type: AWS::CodeBuild::Project
  Properties:
    EncryptionKey: !ImportValue {{$.AppName}}-ArtifactKey
    ServiceRole: !GetAtt BuildProjectRole.Arn
    Artifacts:
      Type: CODEPIPELINE
    {{- if or (eq $action.Build.EnvironmentType "LINUX_CONTAINER") (eq $action.Build.EnvironmentType "ARM_CONTAINER")}}
    Cache:
      Modes:
        - LOCAL_DOCKER_LAYER_CACHE
      Type: LOCAL
    {{- else }}
    Cache:
      Type: "NO_CACHE"
    {{- end }}
    Environment:
      Type: {{$action.Build.EnvironmentType}}
      ComputeType: BUILD_GENERAL1_SMALL
      PrivilegedMode: true
      Image: {{$action.Build.Image}}
      EnvironmentVariables:
        - Name: AWS_ACCOUNT_ID
          Value: !Sub '${AWS::AccountId}'
        - Name: PARTITION
          Value: !Ref AWS::Partition
    Source:
      Type: CODEPIPELINE
      BuildSpec: {{$action.Build.BuildspecPath}}
    TimeoutInMinutes: 60
{{- end}}
{{- end}}