// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

// Package bulletiface provides an interface to enable mocking the AWS Bullet service client
// for testing your code.
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters.
package bulletiface

import (
	"github.com/aws/aws-sdk-go/aws"
	"github.com/aws/aws-sdk-go/aws/request"
	"github.com/aws/copilot-cli/internal/pkg/new-sdk-go/bullet"
)

// BulletAPI provides an interface to enable mocking the
// bullet.Bullet service client's API operation,
// paginators, and waiters. This make unit testing your code that calls out
// to the SDK's service client's calls easier.
//
// The best way to use this interface is so the SDK's service client's calls
// can be stubbed out for unit testing your code with the SDK without needing
// to inject custom request handlers into the SDK's request pipeline.
//
//    // myFunc uses an SDK service client to make a request to
//    // AWS Bullet.
//    func myFunc(svc bulletiface.BulletAPI) bool {
//        // Make svc.CreateConnection request
//    }
//
//    func main() {
//        sess := session.New()
//        svc := bullet.New(sess)
//
//        myFunc(svc)
//    }
//
// In your _test.go file:
//
//    // Define a mock struct to be used in your unit tests of myFunc.
//    type mockBulletClient struct {
//        bulletiface.BulletAPI
//    }
//    func (m *mockBulletClient) CreateConnection(input *bullet.CreateConnectionInput) (*bullet.CreateConnectionOutput, error) {
//        // mock response/functionality
//    }
//
//    func TestMyFunc(t *testing.T) {
//        // Setup Test
//        mockSvc := &mockBulletClient{}
//
//        myfunc(mockSvc)
//
//        // Verify myFunc's functionality
//    }
//
// It is important to note that this interface will have breaking changes
// when the service model is updated and adds new API operations, paginators,
// and waiters. Its suggested to use the pattern above for testing, or using
// tooling to generate mocks to satisfy the interfaces.
type BulletAPI interface {
	CreateConnection(*bullet.CreateConnectionInput) (*bullet.CreateConnectionOutput, error)
	CreateConnectionWithContext(aws.Context, *bullet.CreateConnectionInput, ...request.Option) (*bullet.CreateConnectionOutput, error)
	CreateConnectionRequest(*bullet.CreateConnectionInput) (*request.Request, *bullet.CreateConnectionOutput)

	CreateCustomDomainAssociations(*bullet.CreateCustomDomainAssociationsInput) (*bullet.CreateCustomDomainAssociationsOutput, error)
	CreateCustomDomainAssociationsWithContext(aws.Context, *bullet.CreateCustomDomainAssociationsInput, ...request.Option) (*bullet.CreateCustomDomainAssociationsOutput, error)
	CreateCustomDomainAssociationsRequest(*bullet.CreateCustomDomainAssociationsInput) (*request.Request, *bullet.CreateCustomDomainAssociationsOutput)

	CreateService(*bullet.CreateServiceInput) (*bullet.CreateServiceOutput, error)
	CreateServiceWithContext(aws.Context, *bullet.CreateServiceInput, ...request.Option) (*bullet.CreateServiceOutput, error)
	CreateServiceRequest(*bullet.CreateServiceInput) (*request.Request, *bullet.CreateServiceOutput)

	DeleteConnection(*bullet.DeleteConnectionInput) (*bullet.DeleteConnectionOutput, error)
	DeleteConnectionWithContext(aws.Context, *bullet.DeleteConnectionInput, ...request.Option) (*bullet.DeleteConnectionOutput, error)
	DeleteConnectionRequest(*bullet.DeleteConnectionInput) (*request.Request, *bullet.DeleteConnectionOutput)

	DeleteCustomDomainAssociations(*bullet.DeleteCustomDomainAssociationsInput) (*bullet.DeleteCustomDomainAssociationsOutput, error)
	DeleteCustomDomainAssociationsWithContext(aws.Context, *bullet.DeleteCustomDomainAssociationsInput, ...request.Option) (*bullet.DeleteCustomDomainAssociationsOutput, error)
	DeleteCustomDomainAssociationsRequest(*bullet.DeleteCustomDomainAssociationsInput) (*request.Request, *bullet.DeleteCustomDomainAssociationsOutput)

	DeleteService(*bullet.DeleteServiceInput) (*bullet.DeleteServiceOutput, error)
	DeleteServiceWithContext(aws.Context, *bullet.DeleteServiceInput, ...request.Option) (*bullet.DeleteServiceOutput, error)
	DeleteServiceRequest(*bullet.DeleteServiceInput) (*request.Request, *bullet.DeleteServiceOutput)

	DescribeCustomDomainAssociations(*bullet.DescribeCustomDomainAssociationsInput) (*bullet.DescribeCustomDomainAssociationsOutput, error)
	DescribeCustomDomainAssociationsWithContext(aws.Context, *bullet.DescribeCustomDomainAssociationsInput, ...request.Option) (*bullet.DescribeCustomDomainAssociationsOutput, error)
	DescribeCustomDomainAssociationsRequest(*bullet.DescribeCustomDomainAssociationsInput) (*request.Request, *bullet.DescribeCustomDomainAssociationsOutput)

	DescribeOperation(*bullet.DescribeOperationInput) (*bullet.DescribeOperationOutput, error)
	DescribeOperationWithContext(aws.Context, *bullet.DescribeOperationInput, ...request.Option) (*bullet.DescribeOperationOutput, error)
	DescribeOperationRequest(*bullet.DescribeOperationInput) (*request.Request, *bullet.DescribeOperationOutput)

	DescribeService(*bullet.DescribeServiceInput) (*bullet.DescribeServiceOutput, error)
	DescribeServiceWithContext(aws.Context, *bullet.DescribeServiceInput, ...request.Option) (*bullet.DescribeServiceOutput, error)
	DescribeServiceRequest(*bullet.DescribeServiceInput) (*request.Request, *bullet.DescribeServiceOutput)

	ListConnections(*bullet.ListConnectionsInput) (*bullet.ListConnectionsOutput, error)
	ListConnectionsWithContext(aws.Context, *bullet.ListConnectionsInput, ...request.Option) (*bullet.ListConnectionsOutput, error)
	ListConnectionsRequest(*bullet.ListConnectionsInput) (*request.Request, *bullet.ListConnectionsOutput)

	ListOperations(*bullet.ListOperationsInput) (*bullet.ListOperationsOutput, error)
	ListOperationsWithContext(aws.Context, *bullet.ListOperationsInput, ...request.Option) (*bullet.ListOperationsOutput, error)
	ListOperationsRequest(*bullet.ListOperationsInput) (*request.Request, *bullet.ListOperationsOutput)

	ListServices(*bullet.ListServicesInput) (*bullet.ListServicesOutput, error)
	ListServicesWithContext(aws.Context, *bullet.ListServicesInput, ...request.Option) (*bullet.ListServicesOutput, error)
	ListServicesRequest(*bullet.ListServicesInput) (*request.Request, *bullet.ListServicesOutput)

	ListServicesPages(*bullet.ListServicesInput, func(*bullet.ListServicesOutput, bool) bool) error
	ListServicesPagesWithContext(aws.Context, *bullet.ListServicesInput, func(*bullet.ListServicesOutput, bool) bool, ...request.Option) error

	ListTagsForResource(*bullet.ListTagsForResourceInput) (*bullet.ListTagsForResourceOutput, error)
	ListTagsForResourceWithContext(aws.Context, *bullet.ListTagsForResourceInput, ...request.Option) (*bullet.ListTagsForResourceOutput, error)
	ListTagsForResourceRequest(*bullet.ListTagsForResourceInput) (*request.Request, *bullet.ListTagsForResourceOutput)

	PauseService(*bullet.PauseServiceInput) (*bullet.PauseServiceOutput, error)
	PauseServiceWithContext(aws.Context, *bullet.PauseServiceInput, ...request.Option) (*bullet.PauseServiceOutput, error)
	PauseServiceRequest(*bullet.PauseServiceInput) (*request.Request, *bullet.PauseServiceOutput)

	ResumeService(*bullet.ResumeServiceInput) (*bullet.ResumeServiceOutput, error)
	ResumeServiceWithContext(aws.Context, *bullet.ResumeServiceInput, ...request.Option) (*bullet.ResumeServiceOutput, error)
	ResumeServiceRequest(*bullet.ResumeServiceInput) (*request.Request, *bullet.ResumeServiceOutput)

	StartDeployment(*bullet.StartDeploymentInput) (*bullet.StartDeploymentOutput, error)
	StartDeploymentWithContext(aws.Context, *bullet.StartDeploymentInput, ...request.Option) (*bullet.StartDeploymentOutput, error)
	StartDeploymentRequest(*bullet.StartDeploymentInput) (*request.Request, *bullet.StartDeploymentOutput)

	TagResource(*bullet.TagResourceInput) (*bullet.TagResourceOutput, error)
	TagResourceWithContext(aws.Context, *bullet.TagResourceInput, ...request.Option) (*bullet.TagResourceOutput, error)
	TagResourceRequest(*bullet.TagResourceInput) (*request.Request, *bullet.TagResourceOutput)

	UntagResource(*bullet.UntagResourceInput) (*bullet.UntagResourceOutput, error)
	UntagResourceWithContext(aws.Context, *bullet.UntagResourceInput, ...request.Option) (*bullet.UntagResourceOutput, error)
	UntagResourceRequest(*bullet.UntagResourceInput) (*request.Request, *bullet.UntagResourceOutput)

	UpdateService(*bullet.UpdateServiceInput) (*bullet.UpdateServiceOutput, error)
	UpdateServiceWithContext(aws.Context, *bullet.UpdateServiceInput, ...request.Option) (*bullet.UpdateServiceOutput, error)
	UpdateServiceRequest(*bullet.UpdateServiceInput) (*request.Request, *bullet.UpdateServiceOutput)
}

var _ BulletAPI = (*bullet.Bullet)(nil)
