CertificateValidationFunction:
  Type: AWS::Lambda::Function
  Condition: DelegateDNS
  Properties:
    {{- with $cr := index .CustomResources "CertificateValidationFunction" }}
    Code:
      S3Bucket: {{$cr.Bucket}}
      S3Key: {{$cr.Key}}
    {{- end}}
    Handler: "index.certificateRequestHandler"
    Timeout: 900
    MemorySize: 512
    Role: !GetAtt 'CustomResourceRole.Arn'
    Runtime: nodejs16.x

CustomDomainFunction:
  Condition: ManagedAliases
  Type: AWS::Lambda::Function
  Properties:
    {{- with $cr := index .CustomResources "CustomDomainFunction" }}
    Code:
      S3Bucket: {{$cr.Bucket}}
      S3Key: {{$cr.Key}}
    {{- end}}
    Handler: "index.handler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt 'CustomResourceRole.Arn'
    Runtime: nodejs16.x 

DNSDelegationFunction:
  Type: AWS::Lambda::Function
  Condition: DelegateDNS
  Properties:
    {{- with $cr := index .CustomResources "DNSDelegationFunction" }}
    Code:
      S3Bucket: {{$cr.Bucket}}
      S3Key: {{$cr.Key}}
    {{- end}}
    Handler: "index.domainDelegationHandler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt 'CustomResourceRole.Arn'
    Runtime: nodejs16.x
