# DNS Delegation Resources
CertificateValidationFunction:
  Type: AWS::Lambda::Function
  Condition: DelegateDNS
  Properties:
    Code:
      S3Bucket: {{.ScriptBucketName}}
      S3Key: {{.DNSCertValidatorLambda}}
    Handler: "index.certificateRequestHandler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt 'CustomResourceRole.Arn'
    Runtime: nodejs12.x

DNSDelegationFunction:
  Type: AWS::Lambda::Function
  Condition: DelegateDNS
  Properties:
    Code:
      S3Bucket: {{.ScriptBucketName}}
      S3Key: {{.DNSDelegationLambda}}
    Handler: "index.domainDelegationHandler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt 'CustomResourceRole.Arn'
    Runtime: nodejs12.x

# Resources to enable long ARN formats for the CF execution role.
EnableLongARNFormatFunction:
  Type: AWS::Lambda::Function
  Properties:
    Code:
      S3Bucket: {{.ScriptBucketName}}
      S3Key: {{.EnableLongARNFormatLambda}}
    Handler: "index.handler"
    Timeout: 600
    MemorySize: 512
    Role: !GetAtt 'CloudformationExecutionRole.Arn'
    Runtime: nodejs12.x