// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package bullet

const (

	// ErrCodeInternalServiceErrorException for service response error code
	// "InternalServiceError".
	//
	// An unexpected service exception occurred.
	ErrCodeInternalServiceErrorException = "InternalServiceError"

	// ErrCodeInvalidRequestException for service response error code
	// "InvalidRequest".
	//
	// One or more input parameters aren't valid. Refer to the API action's document
	// page, correct the input parameters, and try the action again.
	ErrCodeInvalidRequestException = "InvalidRequest"

	// ErrCodeInvalidStateException for service response error code
	// "InvalidState".
	//
	// You can't perform this action when the resource is in its current state.
	ErrCodeInvalidStateException = "InvalidState"

	// ErrCodeResourceNotFoundException for service response error code
	// "ResourceNotfound".
	//
	// A resource doesn't exist for the specified Amazon Resource Name (ARN) in
	// your AWS account.
	ErrCodeResourceNotFoundException = "ResourceNotfound"

	// ErrCodeServiceQuotaExceededException for service response error code
	// "ServiceQuotaExceeded".
	//
	// Fusion can't create this resource. You've reached your account quota for
	// this resource type.
	//
	// For Fusion per-resource quotas, see AWS Fusion endpoints and quotas (https://docs.aws.amazon.com/general/latest/gr/fusion.html)
	// in the AWS General Reference.
	ErrCodeServiceQuotaExceededException = "ServiceQuotaExceeded"
)
