# Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template that represents a load balanced web service on Amazon ECS.
Parameters:
  AppName:
    Type: String
  EnvName:
    Type: String
  WorkloadName:
    Type: String
  ContainerImage:
    Type: String
  ContainerPort:
    Type: Number
  TaskCPU:
    Type: String
  TaskMemory:
    Type: String
  TaskCount:
    Type: Number
  DNSDelegated:
    Type: String
    AllowedValues: [true, false]
  LogRetention:
    Type: Number
  AddonsTemplateURL:
    Description: 'URL of the addons nested stack template within the S3 bucket.'
    Type: String
    Default: ""
  EnvFileARN:
    Description: 'URL of the environment file.'
    Type: String
    Default: ""
  TargetContainer:
    Type: String
  TargetPort:
    Type: Number
{{- if not .HTTPDisabled}}
  HTTPSEnabled:
    Type: String
    AllowedValues: [true, false]
  RulePath:
    Type: String
  Stickiness:
    Type: String
    Default: false
{{- end}}
Conditions:
{{- if not .HTTPDisabled}}
  HTTPLoadBalancer:
    !Not
      - !Condition HTTPSLoadBalancer
  HTTPSLoadBalancer:
    !Equals [!Ref HTTPSEnabled, true]
  IsDefaultRootPath:
    !Equals [!Ref RulePath, "/"]
{{- end}}
  HasAssociatedDomain:
    !Equals [!Ref DNSDelegated, true]
  HasAddons: # If a bucket URL is specified, that means the template exists.
    !Not [!Equals [!Ref AddonsTemplateURL, ""]]
  HasEnvFile:
    !Not [!Equals [!Ref EnvFileARN, ""]]
Resources:
{{include "loggroup" . | indent 2}}

  TaskDefinition:
    Metadata:
      'aws:copilot:description': 'An ECS task definition to group your containers and run them on ECS'
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
{{include "fargate-taskdef-base-properties" . | indent 6}}
      ContainerDefinitions:
{{include "workload-container" . | indent 8}}
{{- include "sidecars" . | indent 8}}

{{if .Storage -}}
{{include "volumes" . | indent 6}}
{{- end}}
{{include "executionrole" . | indent 2}}
{{include "taskrole" . | indent 2}}
{{include "servicediscovery" . | indent 2}}
{{- if .Autoscaling}}
{{include "autoscaling" . | indent 2}}
  {{if .Autoscaling.Requests}}
  AutoScalingPolicyALBSumRequestCountPerTarget:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Join ['-', [!Ref WorkloadName, ALBSumRequestCountPerTarget, ScalingPolicy]]
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        CustomizedMetricSpecification:
          Dimensions:
            - Name: LoadBalancer
              Value: !GetAtt EnvControllerAction.PublicLoadBalancerFullName
            - Name: TargetGroup
              Value: !GetAtt TargetGroup.TargetGroupFullName
          MetricName: RequestCountPerTarget
          Namespace: AWS/ApplicationELB
          Statistic: Sum
        ScaleInCooldown: 120
        ScaleOutCooldown: 60
        TargetValue: {{.Autoscaling.Requests}}
  {{- end}}
  {{if .Autoscaling.ResponseTime}}
  AutoScalingPolicyALBAverageResponseTime:
    Type: AWS::ApplicationAutoScaling::ScalingPolicy
    Properties:
      PolicyName: !Join ['-', [!Ref WorkloadName, ALBAverageResponseTime, ScalingPolicy]]
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref AutoScalingTarget
      TargetTrackingScalingPolicyConfiguration:
        CustomizedMetricSpecification:
          Dimensions:
            - Name: LoadBalancer
              Value: !GetAtt EnvControllerAction.PublicLoadBalancerFullName
            - Name: TargetGroup
              Value: !GetAtt TargetGroup.TargetGroupFullName
          MetricName: TargetResponseTime
          Namespace: AWS/ApplicationELB
          Statistic: Average
        ScaleInCooldown: 120
        ScaleOutCooldown: 60
        TargetValue: {{.Autoscaling.ResponseTime}}
  {{- end}}
{{- end}}

{{include "env-controller" . | indent 2}}

  Service:
    Metadata:
      'aws:copilot:description': 'An ECS service to run and maintain your tasks in the environment cluster'
    Type: AWS::ECS::Service
    DependsOn:
    {{- if not .HTTPDisabled}}
     - WaitUntilListenerRuleIsCreated
    {{- end}}
    {{- if .NLB}}
     - NLBListener
    {{- end}}
    Properties:
{{include "service-base-properties" . | indent 6}}
      # This may need to be adjusted if the container takes a while to start up
      HealthCheckGracePeriodSeconds: {{.HTTPHealthCheck.GracePeriod}}
      LoadBalancers:
  {{- if not .HTTPDisabled}}
        - ContainerName: !Ref TargetContainer
          ContainerPort: !Ref TargetPort
          TargetGroupArn: !Ref TargetGroup
  {{- end}}
  {{- if .NLB}}
        - ContainerName: {{.NLB.Listener.TargetContainer}}
          ContainerPort:  {{.NLB.Listener.TargetPort}}
          TargetGroupArn: !Ref NLBTargetGroup
  {{- end}}
      ServiceRegistries:
        - RegistryArn: !GetAtt DiscoveryService.Arn
          Port: !Ref ContainerPort

{{- if not .HTTPDisabled}}
  TargetGroup:
    Metadata:
      'aws:copilot:description': 'A target group to connect the load balancer to your service'
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckPath: {{.HTTPHealthCheck.HealthCheckPath}} # Default is '/'.
{{- if .HTTPHealthCheck.SuccessCodes}}
      Matcher: 
        HttpCode: {{.HTTPHealthCheck.SuccessCodes}}
{{- end}}
{{- if .HTTPHealthCheck.HealthyThreshold}}
      HealthyThresholdCount: {{.HTTPHealthCheck.HealthyThreshold}}
{{- end}}
{{- if .HTTPHealthCheck.UnhealthyThreshold}}
      UnhealthyThresholdCount: {{.HTTPHealthCheck.UnhealthyThreshold}}
{{- end}}
{{- if .HTTPHealthCheck.Interval}}
      HealthCheckIntervalSeconds: {{.HTTPHealthCheck.Interval}}
{{- end}}
{{- if .HTTPHealthCheck.Timeout}}
      HealthCheckTimeoutSeconds: {{.HTTPHealthCheck.Timeout}}
{{- end}}
      Port: !Ref ContainerPort
      Protocol: HTTP
{{- if .HTTPVersion}}
      ProtocolVersion: {{.HTTPVersion}}
{{- end}}
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: {{.DeregistrationDelay}}  # ECS Default is 300; Copilot default is 60.
        - Key: stickiness.enabled
          Value: !Ref Stickiness
      TargetType: ip
      VpcId:
        Fn::ImportValue:
          !Sub "${AppName}-${EnvName}-VpcId"
{{if not .Aliases}}
  LoadBalancerDNSAlias:
    Type: AWS::Route53::RecordSetGroup
    Condition: HTTPSLoadBalancer
    Properties:
      HostedZoneId:
        Fn::ImportValue:
          !Sub "${AppName}-${EnvName}-HostedZone"
      Comment: !Sub "LoadBalancer alias for service ${WorkloadName}"
      RecordSets:
      - Name:
          !Join
            - '.'
            - - !Ref WorkloadName
              - Fn::ImportValue:
                  !Sub "${AppName}-${EnvName}-SubDomain"
              - ""
        Type: A
        AliasTarget:
          HostedZoneId: !GetAtt EnvControllerAction.PublicLoadBalancerHostedZone
          DNSName: !GetAtt EnvControllerAction.PublicLoadBalancerDNSName
{{end}}
  RulePriorityFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          {{.RulePriorityLambda}}
      Handler: "index.nextAvailableRulePriorityHandler"
      Timeout: 600
      MemorySize: 512
      Role: !GetAtt 'CustomResourceRole.Arn'
      Runtime: nodejs12.x

  CustomResourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: "DNSandACMAccess"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - elasticloadbalancing:DescribeRules
              Resource: "*"
{{- if .Autoscaling }}
        - PolicyName: "DelegateDesiredCountAccess"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: ECS
              Effect: Allow
              Action:
                - ecs:DescribeServices
              Resource: "*"
              Condition: 
                ArnEquals: 
                  'ecs:cluster':
                    Fn::Sub:
                      - arn:${AWS::Partition}:ecs:${AWS::Region}:${AWS::AccountId}:cluster/${ClusterName}
                      - ClusterName:
                          Fn::ImportValue:
                            !Sub '${AppName}-${EnvName}-ClusterId'
            - Sid: ResourceGroups
              Effect: Allow
              Action:
                - resource-groups:GetResources
              Resource: "*"
            - Sid: Tags
              Effect: Allow
              Action:
                - "tag:GetResources"
              Resource: "*"
{{- end}}
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  HTTPSRulePriorityAction:
    Condition: HTTPSLoadBalancer
    Type: Custom::RulePriorityFunction
    Properties:
      ServiceToken: !GetAtt RulePriorityFunction.Arn
      ListenerArn: !GetAtt EnvControllerAction.HTTPSListenerArn

  HTTPListenerRuleWithDomain:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HTTPSLoadBalancer
    Properties:
      Actions:
        - Type: redirect
          RedirectConfig:
            Protocol: HTTPS
            Port: 443
            Host: "#{host}"
            Path: "/#{path}"
            Query: "#{query}"
            StatusCode: HTTP_301
      Conditions:
{{- if .Aliases }}
        - Field: 'host-header'
          HostHeaderConfig:
            Values: {{ fmtSlice .Aliases }}
{{- else }}
        - Field: 'host-header'
          HostHeaderConfig:
            Values:
              - Fn::Join:
                - '.'
                - - !Ref WorkloadName
                  - Fn::ImportValue:
                      !Sub "${AppName}-${EnvName}-SubDomain"
{{- end}}
        - Field: 'path-pattern'
          PathPatternConfig:
            Values:
              !If
                - IsDefaultRootPath
                -
                  - "/*"
                -
                  - !Sub "/${RulePath}"
                  - !Sub "/${RulePath}/*"
      ListenerArn: !GetAtt EnvControllerAction.HTTPListenerArn
      Priority: !GetAtt HTTPSRulePriorityAction.Priority # Same priority as HTTPS Listener

  HTTPSListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HTTPSLoadBalancer
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
{{- if .AllowedSourceIps}}
        - Field: 'source-ip'
          SourceIpConfig:
            Values:
{{- range $sourceIP := .AllowedSourceIps}}
            - {{$sourceIP}}
{{- end}}
{{- end}}
{{- if .Aliases }}
        - Field: 'host-header'
          HostHeaderConfig:
            Values: {{ fmtSlice .Aliases }}
{{- else }}
        - Field: 'host-header'
          HostHeaderConfig:
            Values:
              - Fn::Join:
                - '.'
                - - !Ref WorkloadName
                  - Fn::ImportValue:
                      !Sub "${AppName}-${EnvName}-SubDomain"
{{- end}}
        - Field: 'path-pattern'
          PathPatternConfig:
            Values:
              !If
                - IsDefaultRootPath
                -
                  - "/*"
                -
                  - !Sub "/${RulePath}"
                  - !Sub "/${RulePath}/*"
      ListenerArn: !GetAtt EnvControllerAction.HTTPSListenerArn
      Priority: !GetAtt HTTPSRulePriorityAction.Priority

  HTTPRulePriorityAction:
    Condition: HTTPLoadBalancer
    Type: Custom::RulePriorityFunction
    Properties:
      ServiceToken: !GetAtt RulePriorityFunction.Arn
      ListenerArn: !GetAtt EnvControllerAction.HTTPListenerArn

  HTTPListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Condition: HTTPLoadBalancer
    Properties:
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward
      Conditions:
      {{- if .AllowedSourceIps}}
        - Field: 'source-ip'
          SourceIpConfig:
            Values:
            {{- range $sourceIP := .AllowedSourceIps}}
            - {{$sourceIP}}
            {{- end}}
      {{- end}}
        - Field: 'path-pattern'
          PathPatternConfig:
            Values:
              !If
                - IsDefaultRootPath
                -
                  - "/*"
                -
                  - !Sub "/${RulePath}"
                  - !Sub "/${RulePath}/*"
      ListenerArn: !GetAtt EnvControllerAction.HTTPListenerArn
      Priority: 
        !If
          - IsDefaultRootPath
          - 50000 # This is the max rule priority. Since this rule evaluates true for everything, we make sure it is last
          - !GetAtt HTTPRulePriorityAction.Priority

  # Force a conditional dependency from the ECS service on the listener rules.
  # Our service depends on our HTTP/S listener to be set up before it can
  # be created. But, since our environment is either HTTPS or not, we
  # have a conditional dependency (we have to wait for the HTTPS listener
  # to be created or the HTTP listener to be created). In order to have a
  # conditional dependency, we use the WaitHandle resource as a way to force
  # a single dependency. The Ref in the WaitCondition implicitly creates a conditional
  # dependency - if the condition is satisfied (HTTPLoadBalancer) - the ref resolves
  # the HTTPWaitHandle, which depends on the HTTPListenerRule.

  HTTPSWaitHandle:
    Condition: HTTPSLoadBalancer
    DependsOn: HTTPSListenerRule
    Type: AWS::CloudFormation::WaitConditionHandle

  HTTPWaitHandle:
    Condition: HTTPLoadBalancer
    DependsOn: HTTPListenerRule
    Type: AWS::CloudFormation::WaitConditionHandle

  # We don't actually need to wait for the condition to
  # be completed, that's why we set a count of 0. The timeout
  # is a required field, but useless, so we set it to one.
  WaitUntilListenerRuleIsCreated:
    Type: AWS::CloudFormation::WaitCondition
    Properties:
      Handle: !If [HTTPLoadBalancer, !Ref HTTPWaitHandle, !Ref HTTPSWaitHandle]
      Timeout: "1"
      Count: 0

{{- end}} {{/*end if not .HTTPDisabled */}}
{{- if .NLB}}
{{include "nlb" . | indent 2}}
{{- end}}

{{include "efs-access-point" . | indent 2}}

{{include "addons" . | indent 2}}

{{include "publish" . | indent 2}}

Outputs:
  DiscoveryServiceARN:
    Description: ARN of the Discovery Service.
    Value: !GetAtt DiscoveryService.Arn
    Export:
      Name: !Sub ${AWS::StackName}-DiscoveryServiceARN
