// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/runner/job/job_runner.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cloudformation "github.com/aws/copilot-cli/internal/pkg/aws/cloudformation"
	gomock "github.com/golang/mock/gomock"
)

// MockJobExecutor is a mock of JobExecutor interface.
type MockJobExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockJobExecutorMockRecorder
}

// MockJobExecutorMockRecorder is the mock recorder for MockJobExecutor.
type MockJobExecutorMockRecorder struct {
	mock *MockJobExecutor
}

// NewMockJobExecutor creates a new mock instance.
func NewMockJobExecutor(ctrl *gomock.Controller) *MockJobExecutor {
	mock := &MockJobExecutor{ctrl: ctrl}
	mock.recorder = &MockJobExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobExecutor) EXPECT() *MockJobExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockJobExecutor) Execute(stateMachineARN string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", stateMachineARN)
	ret0, _ := ret[0].(error)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockJobExecutorMockRecorder) Execute(stateMachineARN interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockJobExecutor)(nil).Execute), stateMachineARN)
}

// MockStackRetriever is a mock of StackRetriever interface.
type MockStackRetriever struct {
	ctrl     *gomock.Controller
	recorder *MockStackRetrieverMockRecorder
}

// MockStackRetrieverMockRecorder is the mock recorder for MockStackRetriever.
type MockStackRetrieverMockRecorder struct {
	mock *MockStackRetriever
}

// NewMockStackRetriever creates a new mock instance.
func NewMockStackRetriever(ctrl *gomock.Controller) *MockStackRetriever {
	mock := &MockStackRetriever{ctrl: ctrl}
	mock.recorder = &MockStackRetrieverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStackRetriever) EXPECT() *MockStackRetrieverMockRecorder {
	return m.recorder
}

// StackResources mocks base method.
func (m *MockStackRetriever) StackResources(name string) ([]*cloudformation.StackResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StackResources", name)
	ret0, _ := ret[0].([]*cloudformation.StackResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StackResources indicates an expected call of StackResources.
func (mr *MockStackRetrieverMockRecorder) StackResources(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StackResources", reflect.TypeOf((*MockStackRetriever)(nil).StackResources), name)
}
