// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/deploy/cloudformation/stack/backend_app.go

// Package mocks is a generated GoMock package.
package mocks

import (
	template "github.com/aws/amazon-ecs-cli-v2/internal/pkg/template"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockbackendAppReadParser is a mock of backendAppReadParser interface
type MockbackendAppReadParser struct {
	ctrl     *gomock.Controller
	recorder *MockbackendAppReadParserMockRecorder
}

// MockbackendAppReadParserMockRecorder is the mock recorder for MockbackendAppReadParser
type MockbackendAppReadParserMockRecorder struct {
	mock *MockbackendAppReadParser
}

// NewMockbackendAppReadParser creates a new mock instance
func NewMockbackendAppReadParser(ctrl *gomock.Controller) *MockbackendAppReadParser {
	mock := &MockbackendAppReadParser{ctrl: ctrl}
	mock.recorder = &MockbackendAppReadParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockbackendAppReadParser) EXPECT() *MockbackendAppReadParserMockRecorder {
	return m.recorder
}

// Read mocks base method
func (m *MockbackendAppReadParser) Read(path string) (*template.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path)
	ret0, _ := ret[0].(*template.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockbackendAppReadParserMockRecorder) Read(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockbackendAppReadParser)(nil).Read), path)
}

// Parse mocks base method
func (m *MockbackendAppReadParser) Parse(path string, data interface{}, options ...template.ParseOption) (*template.Content, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{path, data}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Parse", varargs...)
	ret0, _ := ret[0].(*template.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse
func (mr *MockbackendAppReadParserMockRecorder) Parse(path, data interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{path, data}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockbackendAppReadParser)(nil).Parse), varargs...)
}

// ParseBackendService mocks base method
func (m *MockbackendAppReadParser) ParseBackendService(arg0 template.ServiceOpts) (*template.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseBackendService", arg0)
	ret0, _ := ret[0].(*template.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseBackendService indicates an expected call of ParseBackendService
func (mr *MockbackendAppReadParserMockRecorder) ParseBackendService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseBackendService", reflect.TypeOf((*MockbackendAppReadParser)(nil).ParseBackendService), arg0)
}
