// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/pkg/deploy/cloudformation/stack/lb_web_svc.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	template "github.com/aws/copilot-cli/internal/pkg/template"
	gomock "github.com/golang/mock/gomock"
)

// MockloadBalancedWebSvcReadParser is a mock of loadBalancedWebSvcReadParser interface
type MockloadBalancedWebSvcReadParser struct {
	ctrl     *gomock.Controller
	recorder *MockloadBalancedWebSvcReadParserMockRecorder
}

// MockloadBalancedWebSvcReadParserMockRecorder is the mock recorder for MockloadBalancedWebSvcReadParser
type MockloadBalancedWebSvcReadParserMockRecorder struct {
	mock *MockloadBalancedWebSvcReadParser
}

// NewMockloadBalancedWebSvcReadParser creates a new mock instance
func NewMockloadBalancedWebSvcReadParser(ctrl *gomock.Controller) *MockloadBalancedWebSvcReadParser {
	mock := &MockloadBalancedWebSvcReadParser{ctrl: ctrl}
	mock.recorder = &MockloadBalancedWebSvcReadParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockloadBalancedWebSvcReadParser) EXPECT() *MockloadBalancedWebSvcReadParserMockRecorder {
	return m.recorder
}

// Read mocks base method
func (m *MockloadBalancedWebSvcReadParser) Read(path string) (*template.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", path)
	ret0, _ := ret[0].(*template.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockloadBalancedWebSvcReadParserMockRecorder) Read(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockloadBalancedWebSvcReadParser)(nil).Read), path)
}

// Parse mocks base method
func (m *MockloadBalancedWebSvcReadParser) Parse(path string, data interface{}, options ...template.ParseOption) (*template.Content, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{path, data}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Parse", varargs...)
	ret0, _ := ret[0].(*template.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Parse indicates an expected call of Parse
func (mr *MockloadBalancedWebSvcReadParserMockRecorder) Parse(path, data interface{}, options ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{path, data}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Parse", reflect.TypeOf((*MockloadBalancedWebSvcReadParser)(nil).Parse), varargs...)
}

// ParseLoadBalancedWebService mocks base method
func (m *MockloadBalancedWebSvcReadParser) ParseLoadBalancedWebService(arg0 template.ServiceOpts) (*template.Content, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseLoadBalancedWebService", arg0)
	ret0, _ := ret[0].(*template.Content)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseLoadBalancedWebService indicates an expected call of ParseLoadBalancedWebService
func (mr *MockloadBalancedWebSvcReadParserMockRecorder) ParseLoadBalancedWebService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseLoadBalancedWebService", reflect.TypeOf((*MockloadBalancedWebSvcReadParser)(nil).ParseLoadBalancedWebService), arg0)
}
