name: codecov

on:
  push:
    branches:
      - "mainline"
      - "test/cov"

jobs:
  test-cov:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

      - name: Upload golang coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out
          verbose: true

      - name: Upload node coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          directory: cf-custom-resources/
          verbose: true
