name: codecov

on:
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline
    types:
      - opened
      - edited
      - synchronize

jobs:
  test-cov:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run tests
        run: make test

      - name: Upload golang coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.out

      - name: Upload node coverage report to CodeCov
        uses: codecov/codecov-action@v3
        with:
          directory: cf-custom-resources/

      - name: Get coverage report from CodeCov
        run: |
          curl --location --request POST 'https://api.codecov.io/graphql/gh' \
            --header 'cache-control: no-cache' \
            --header 'Content-Type: application/json' \
            --data-raw '{"query":"query GetCommits($owner: String!, $repo: String!, $filters:CommitsSetFilters, $after: String){owner (username:$owner) {repository (name: $repo) {commits (filters: $filters, first: 2, after: $after) {edges{node{...CommitFragment}}}}}}\nfragment CommitFragment on Commit {commitid createdAt totals{coverage} parent {totals{coverage}}}","variables":{"owner":"${{ github.repository_owner }}","repo":"copilot-cli"}}'
